# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d7d7287e12a05e37d1f361605c096ac507d8f726dc43cc0b84353bca0f247b23f4a9d64370b37bebc2d1d5d5347e23ec6070ae5cccbd7e3bcf827880415453b4
  stripe_publishable_key: pk_test_Jy1EkOOs0HZPvZeNTJgEyxWJ
  stripe_secret_key: sk_test_9RQld2SBZ5bwUFymfauCMQWp

test:
  secret_key_base: 730ad7ac4de0dae12a1055b5b61c4f4ff1b639410f16d53a6f4c8b54203c9d5577dfc657eadba02da1079bb492f4ba72fbab3cca226caa2f5b3f70e7875ce76c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: <%= ENV["STRIPE_PUBLISHABLE_KEY"] %> 
  stripe_api_key: <%= ENV["STRIPE_API_KEY"] %> 


#heroku config:set PUBLISHABLE_KEY=pk_test_Jy1EkOOs0HZPvZeNTJgEyxWJ SECRET_KEY=sk_test_9RQld2SBZ5bwUFymfauCMQWp